spring:
  application:
    name: springai-kata
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
  # Enable OpenAI optimized model for embeddings
      embedding:
        options:
          model: text-embedding-3-small

# /api-docs endpoint custom path
springdoc:
  api-docs:
    path: /api-docs

# Vector Store for RAG  
sfg:
  aiapp:
    vectorStorePath: /tmp/vectorstore.json
    documentsToLoad:
      - /datasets/movies500.csv